import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [content, setContent] = useState(() => <div>Loading...</div>);

  const mount = async () => {
    if (typeof window !== "undefined") {
      const { MapView } = await import('../components/mappedin');
      setContent(() => <MapView />);
    }
  };

  useEffect(() => {
    mount();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {content}
      </main>
    </div>
  );
}
